# Generated by Django 5.2.8 on 2025-11-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Category Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstallPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Phase Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Install Phase',
                'verbose_name_plural': 'Install Phases',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='SubCategory Name')),
                ('image', models.ImageField(blank=True, upload_to='subcategories/', verbose_name='SubCategory Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='packages.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Package Name')),
                ('image', models.ImageField(blank=True, upload_to='packages/', verbose_name='Package Image')),
                ('description', models.TextField(help_text="What's included", verbose_name='Description')),
                ('price_low', models.DecimalField(decimal_places=2, help_text='Estimated price range - low', max_digits=10, verbose_name='Price Low')),
                ('price_high', models.DecimalField(decimal_places=2, help_text='Estimated price range - high', max_digits=10, verbose_name='Price High')),
                ('price_notes', models.TextField(blank=True, help_text='Disclaimers/asterisks', verbose_name='Price Notes')),
                ('bundle_discount_note', models.CharField(blank=True, help_text='e.g., Save $X when combined with Y', max_length=255, verbose_name='Bundle Discount Note')),
                ('utility_incentive_eligible', models.BooleanField(default=False, help_text='Eligible for utility incentives', verbose_name='Utility Incentive Eligible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.category', verbose_name='Category')),
                ('install_phases', models.ManyToManyField(blank=True, related_name='packages', to='packages.installphase', verbose_name='Install Phases')),
                ('requires_phase', models.ForeignKey(blank=True, help_text='Installation phase this package requires', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by_packages', to='packages.installphase', verbose_name='Required Phase')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Not mandatory for package build', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.subcategory', verbose_name='SubCategory')),
            ],
            options={
                'verbose_name': 'Package Template',
                'verbose_name_plural': 'Package Templates',
                'ordering': ['category', 'subcategory', 'name'],
            },
        ),
    ]
