# Generated by Django 5.2.8 on 2025-11-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(help_text='Auto-generated (e.g., EST-2024-001)', max_length=50, unique=True, verbose_name='Estimate Number')),
                ('client_name', models.CharField(blank=True, help_text='Homeowner name', max_length=255, verbose_name='Client Name')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Client Email')),
                ('total_low', models.DecimalField(decimal_places=2, help_text='Sum of price_low', max_digits=12, verbose_name='Total Low')),
                ('total_high', models.DecimalField(decimal_places=2, help_text='Sum of price_high', max_digits=12, verbose_name='Total High')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('archived', 'Archived')], default='pending', max_length=20, verbose_name='Status')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL, verbose_name='Builder')),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_low_snapshot', models.DecimalField(decimal_places=2, help_text='Snapshot at time of estimate', max_digits=10, verbose_name='Price Low Snapshot')),
                ('price_high_snapshot', models.DecimalField(decimal_places=2, help_text='Snapshot at time of estimate', max_digits=10, verbose_name='Price High Snapshot')),
                ('package_name_snapshot', models.CharField(help_text='In case package is deleted/renamed', max_length=255, verbose_name='Package Name Snapshot')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimate', verbose_name='Estimate')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagetemplate', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Estimate Item',
                'verbose_name_plural': 'Estimate Items',
                'unique_together': {('estimate', 'package')},
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='packages',
            field=models.ManyToManyField(related_name='estimates', through='estimates.EstimateItem', to='packages.packagetemplate', verbose_name='Packages'),
        ),
    ]
