# Generated by Django 5.2.8 on 2025-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Profile Created At'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Profile Updated At'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
